### ISSUE TITLE
localでgolang APIに切り替える

### ISSUE THREAD

**Issue by myantyuWorld** [myantyuWorld/kaimemo-next-js#5]
# 関連
- https://github.com/myantyuWorld/kaimemo-next-js/issues/4

# task
- [ ] localにDB構築（コンテナ）
- [ ] DBマイグレーションを行えるようにする
- [ ] get memo　移植
- [ ] post memo　移植
- [ ] delete memo　移植

画像から数字を解析するAPI（gateway + lambda + recognition）は削除まではしないが、移行はしない
（goへのAWS SDK組み込み、の体験もできるので、余裕があれば移行したいが、そもそも精度がゴミで使っていない機能なので削っちゃってもいい？）
